language: csharp
solution: DnDGen.RollGen.sln
mono: none
dotnet: 3.1

script:
  - dotnet build DnDGen.RollGen.sln -c Release
    && dotnet test ./DnDGen.RollGen.Tests.Unit/DnDGen.RollGen.Tests.Unit.csproj -v normal
    && dotnet test ./DnDGen.RollGen.Tests.Integration.IoC/DnDGen.RollGen.Tests.Integration.IoC.csproj -v normal
    && dotnet test ./DnDGen.RollGen.Tests.Integration/DnDGen.RollGen.Tests.Integration.csproj -v normal
    && dotnet test ./DnDGen.RollGen.Tests.Integration.Stress/DnDGen.RollGen.Tests.Integration.Stress.csproj -v normal -c Stress

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: master
