pool:
  vmImage: 'windows-latest'

variables:
  solution: 'DnDGen.RollGen.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  displayName: 'Checkout Code'
  persistCredentials: true
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: 'DnDGen.RollGen/DnDGen.RollGen.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Unit Tests
  inputs:
    command: test
    projects: 'DnDGen.RollGen.Tests.Unit/DnDGen.RollGen.Tests.Unit.csproj'
    arguments: '-v normal'
- task: DotNetCoreCLI@2
  displayName: IoC Tests
  inputs:
    command: test
    projects: 'DnDGen.RollGen.Tests.Integration.IoC/DnDGen.RollGen.Tests.Integration.IoC.csproj'
    arguments: '-v normal'
- task: DotNetCoreCLI@2
  displayName: Integration Tests
  inputs:
    command: test
    projects: 'DnDGen.RollGen.Tests.Integration/DnDGen.RollGen.Tests.Integration.csproj'
    arguments: '-v normal'
- task: DotNetCoreCLI@2
  displayName: Stress Tests
  inputs:
    command: test
    projects: 'DnDGen.RollGen.Tests.Integration.Stress/DnDGen.RollGen.Tests.Integration.Stress.csproj'
    arguments: '-v normal --configuration Stress'

- task: tmarkovski.projectversionasvariable.versionintovariable.projectversionasvariable@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'Get Project Version'
  inputs:
    path: DnDGen.RollGen/DnDGen.RollGen.csproj
    
- script: |
     echo "Tagging with version $(Version.MajorMinorBuild)"
     git tag $(Version.MajorMinorBuild)
     git push origin $(Version.MajorMinorBuild)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'Tag Version'
  workingDirectory: $(Build.SourcesDirectory)

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Publish Artifacts
  inputs:
    pathtoPublish: './DnDGen.RollGen/bin/Release' 
    artifactName: 'dndgen-rollgen'
